// Servizi applicativi OS-agnostici (parlano solo con CLI cross-platform o std).
pub mod clipboard;
pub mod clipboard_cache;
pub mod dotnet;
pub mod drop;
pub mod env;
pub mod git;
pub mod hubdiscovery;
pub mod launch;
pub mod logtail;
pub mod metrics;
pub mod nettools;
pub mod node;
pub mod online;
pub mod projects;
pub mod runners;
pub mod snippets;
pub mod ssh;
pub mod tlscert;
